# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91f7d88284f590b3596462470783a7b4b5c48eddb3ae370396cd392cfe64ee0dbf949f9103123d7312e75ad2653391876352b3c8bad82c0387465f6910a1cb12

test:
  secret_key_base: d465a64523d0301dfe9c9cd0fe4b97450e546dcac20caf452161ca296a0fe51a2a9dd4f45ceb9d9fa04222dea1bdbe7515180576b70adf5392632c64fafd67e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
